name: www.reimedispa.com
favicon: null
layout_spectrum: 0.23373437579721212
typography_spectrum: 0.43110127095133066
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6406068850774318
  lightness: 0.0371174153406173
  saturation: 0.25827940134331584
  rhythmicContrast: 0.6230629137717187
purpose: []
